import { Route, Routes } from "react-router-dom";

import About from "pages/About";
import Contact from "pages/Contact";
import ProjectDetails from "pages/ProjectDetails";
import Projects from "pages/Projects";
import Resume from "pages/Resume";

export default function PortfolioRoutes() {
  const projects = [
    {
      id: 1,
      name: "Netflix Clone",
      image: "/assets/projects/netflix/1.png",
      link: "https://netflex-nine.vercel.app/",
      logo: "/assets/projects/netflix/netflixlogo.png",
      github: "https://github.com/ahmedalianz/netflix-Clone",
      filter: ["React", "SCSS"],
      images: [
        "/assets/projects/netflix/1.png",
        "/assets/projects/netflix/2.png",
        "/assets/projects/netflix/3.png",
        "/assets/projects/netflix/5.png",
        "/assets/projects/netflix/6.png",
        "/assets/projects/netflix/8.png",
      ],
      desc: "This Application Fetches the Popular Movies and Tv Shows From TMDB ,It's The Same Design Style As The Real Netflix , Manually Customized Components like Accordion & Floating Input Without any external Library , It Supports Two Languages (English & Arabic), It's Also Very responsive Design",
    },
    {
      id: 2,
      name: "Sprout Social",
      image: "/assets/projects/sprout/1.png",
      link: "https://sprout-social.vercel.app/",
      logo: "/assets/projects/sprout/sproutlogo.png",
      github: "https://github.com/ahmedalianz/social-React-Redux-MogoDb",
      filter: ["React", "Redux", "Node", "Express", "MongoDB"],
      images: [
        "/assets/projects/sprout/1.png",
        "/assets/projects/sprout/2.png",
        "/assets/projects/sprout/3.png",
        "/assets/projects/sprout/4.png",
      ],
      desc: "In This Application You Can Sign up or login to your account , You can create a post , like it , comment on it ,search for people,view & Edit Your Profile , and more , It's also very responsive Design",
    },
    {
      id: 3,
      name: "Electronics Store",
      image: "/assets/projects/store/1.png",
      link: "https://electronicz-store.vercel.app/",
      logo: "/assets/projects/store/storelogo.png",
      github: "https://github.com/ahmedalianz/E-commerce-react-redux",
      filter: ["React", "Redux", "Node", "Express", "MongoDB"],
      images: [
        "/assets/projects/store/1.png",
        "/assets/projects/store/2.png",
        "/assets/projects/store/3.png",
        "/assets/projects/store/4.png",
        "/assets/projects/store/5.png",
        "/assets/projects/store/6.png",
        "/assets/projects/store/7.png",
        "/assets/projects/store/8.png",
      ],
      desc: "In This Application You Can view all the products , add to cart , checkout , and more ,it Supports Arabic Language, It's also very responsive Design",
    },
    {
      id: 4,
      name: "Pizza Ordering App",
      image: "/assets/projects/pizza/1.png",
      link: "https://pizza-sooty.vercel.app/",
      filter: ["React", "Redux", "Next"],
      images: [
        "/assets/projects/pizza/1.png",
        "/assets/projects/pizza/2.png",
        "/assets/projects/pizza/3.png",
        "/assets/projects/pizza/4.png",
        "/assets/projects/pizza/5.png",
        "/assets/projects/pizza/6.png",
        "/assets/projects/pizza/7.png",
        "/assets/projects/pizza/8.png",
        "/assets/projects/pizza/9.png",
        "/assets/projects/pizza/10.png",
        "/assets/projects/pizza/11.png",
      ],
      desc: "In This Application You Can Order Pizza , You can add Topping , Add To Cart , Checkout ,you can pay cash or via paypal,the admin can contol products & orders create new Pizzas and more , It Supports Two Languages (English & Arabic),  It's also very responsive Design",
    },
    {
      id: 5,
      name: "Deer Fitness",
      image: "/assets/projects/deer.png",
      link: "https://deer-fitness.vercel.app/",
      filter: ["React", "MERN"],
      images: ["/assets/projects/deer.png"],
      desc: "This Application is Made for a Gym so that it's participants can make reservations easily  , It Supports Arabic Languages,  It's also very responsive Design",
    },
    {
      id: 6,
      name: "Shareable To Do App",
      image: "/assets/projects/shareable.png",
      link: "https://sharable-to-do.vercel.app/",
      filter: ["React"],
      images: ["/assets/projects/shareable.png"],
      desc: "In This Application You Can you can create any user by just name so lists are just for your username, Every username has his own lists & able to : Create a New list,Add List Items,Navigate Between Lists,Share Any List By Several Means eg:facebook,whatsapp,direct link,  It's also very responsive Design",
    },
    {
      id: 18,
      name: "Agency",
      image: "/assets/projects/agency.png",
      link: "https://agency-beta.vercel.app/",
      filter: ["React", "Landing Page"],
      images: ["/assets/projects/agency.png"],
      desc: "Its a Landing Page",
    },
    {
      id: 19,
      name: "Manage",
      image: "/assets/projects/manage.png",
      link: "https://ahmedalianz.github.io/manage-landing-page/",
      filter: ["Landing Page"],
      images: ["/assets/projects/manage.png"],
      desc: "Its a Landing Page",
    },
    {
      id: 20,
      name: "EasyBank",
      image: "/assets/projects/easy.png",
      link: "https://ahmedalianz.github.io/easybank-landing-page/",
      filter: ["Landing Page"],
      images: ["/assets/projects/easy.png"],
      desc: "Its a Landing Page",
    },
    {
      id: 21,
      name: "Huddle",
      image: "/assets/projects/huddle.png",
      link: "https://ahmedalianz.github.io/huddle-landing-page/",
      filter: ["Landing Page"],
      images: ["/assets/projects/huddle.png"],
      desc: "Its a Landing Page",
    },
    {
      id: 22,
      name: "Kanban Board",
      image: "/assets/projects/kanban.png",
      link: "https://kanban-boardz.netlify.app/",
      filter: ["Angular"],
      images: ["/assets/projects/kanban.png"],
      desc: "Its a Kanban Board to sort tasks",
    },
    {
      id: 7,
      name: "Bloger",
      image: "/assets/projects/bloger.png",
      link: "https://ahmedalianz.github.io/blogr/",
      filter: ["Landing Page"],
      images: ["/assets/projects/bloger.png"],
      desc: "Its a Landing Page",
    },
    {
      id: 8,
      name: "Lion",
      image: "/assets/projects/lion.png",
      link: "https://ahmedalianz.github.io/Lion-HTML-CSS/",
      filter: ["Landing Page"],
      images: ["/assets/projects/lion.png"],
      desc: "Its a Landing Page",
    },
    {
      id: 9,
      name: "Studio VR",
      image: "/assets/projects/studio.png",
      link: "https://ahmedalianz.github.io/studio-vr/",
      filter: ["Landing Page"],
      images: ["/assets/projects/studio.png"],
      desc: "Its a Landing Page",
    },
    {
      id: 10,
      name: "ClipBoard",
      image: "/assets/projects/clipboard.png",
      link: "https://ahmedalianz.github.io/clipboard/",
      filter: ["Landing Page"],
      images: ["/assets/projects/clipboard.png"],
      desc: "Its a Landing Page",
    },
    {
      id: 11,
      name: "Breaking Bad Cast",
      image: "/assets/projects/breaking.png",
      link: "https://breaking-bad-castz.netlify.app/",
      filter: ["React"],
      images: ["/assets/projects/breaking.png"],
      desc: "In This Application You Can view all the characters , Search for any one of these characters",
    },
    {
      id: 12,
      name: "Menu Mangment",
      image: "/assets/projects/cart.png",
      link: "https://shopping-cart22.netlify.app/",
      filter: ["React"],
      images: ["/assets/projects/cart.png"],
      desc: "In This Application You Can view all the products , add to cart , edit products , and more",
    },
    {
      id: 13,
      name: "My Reads",
      image: "/assets/projects/reads.png",
      link: "https://my-readsz1.netlify.app/",
      filter: ["React"],
      images: ["/assets/projects/reads.png"],
      desc: "In This Application You Can Add Books to Your Reading list & search for any books by it's title or author",
    },
    {
      id: 14,
      name: "Calculator",
      image: "/assets/projects/calculator.png",
      link: "https://ahmedalianz.github.io/calculator-JS/",
      filter: [],
      images: ["/assets/projects/calculator.png"],
      desc: "Its a simple Calculator",
    },
    {
      id: 15,
      name: "SunnySide",
      image: "/assets/projects/sunny.png",
      link: "https://ahmedalianz.github.io/sunnyside/",
      filter: ["Landing Page"],
      images: ["/assets/projects/sunny.png"],
      desc: "Its a Landing Page",
    },
    {
      id: 16,
      name: "Expense Tracker",
      image: "/assets/projects/expense.png",
      link: "https://ahmedalianz.github.io/Expense-tracker-JS/",
      filter: [],
      images: ["/assets/projects/expense.png"],
      desc: "In This Application You Can Add You Salary and expenses so you can track them",
    },
    {
      id: 17,
      name: "News Reader AI",
      image: "/assets/projects/news.png",
      link: "https://ahmedalianz.github.io/Expense-tracker-JS/",
      filter: ["React"],
      images: ["/assets/projects/news.png"],
      desc: "In This Application You Can Search for new by just saying the word and it will show you the news",
    },
  ];
  return (
    <Routes>
      <Route path="/" element={<About />} />
      <Route path="/resume" element={<Resume />} />
      <Route path="/contact" element={<Contact />} />
      <Route path="/projects" element={<Projects projects={projects} />} />
      <Route
        path="/projects/:id"
        element={<ProjectDetails projects={projects} />}
      />
    </Routes>
  );
}
